### PR TITLE
French Translation

### PR DESCRIPTION
**Pull request by Weyland2093**
Updated french translation for new items.

### CODE REVIEW

**Review by mcadam — APPROVED** [review]

**Comment by veado** [comment]
Thx @Weyland2093, your changes will be part of upcoming release.

**Comment by veado** [comment]
@Weyland2093 Can you open another PR for same changes, but checking out `develop` before into a branch `feature/update-fr-translation` (or name it whatever you want)? Based on our "Protect matching branches rules", you do need to create a branch from it first to trigger and pass CI and to merge something after it into `develop`,

**Comment by Weyland2093** [comment]
I have tried all thoses combination, but i can not click on Pull Request. (Sorry, i am not a dev ! Just a Thorchain fan)

**Comment by veado** [comment]
Closed in favour of https://github.com/thorchain/asgardex-electron/pull/1147 to run CI before merging.

**Pull request closed without merging**
